<?php
/**
 * This class was automatically generated by GraphQL Schema generator
 */

namespace AppGraphQLBundle\GraphQL;

use Youshido\GraphQL\Schema\AbstractSchema;
use Youshido\GraphQL\Config\Schema\SchemaConfig;
use Youshido\GraphQL\Type\ListType\ListType;
use Youshido\GraphQL\Type\NonNullType;
use Youshido\GraphQL\Type\Scalar\IntType;
use AppGraphQLBundle\GraphQL\Type\PostType;
use Youshido\GraphQL\Type\Scalar\StringType;

class Schema extends AbstractSchema
{
    public function build(SchemaConfig $config)
    {
        $config->getQuery()->addFields([
            'post' => [
                'type'    => new PostType(),
                'args'    => [
                    'id' => [
                        'type' => new NonNullType(new IntType())
                    ]
                ],
                'resolve' => ['@app_graph_ql.resolver.post', 'find']
            ],
            'postList' => [
                'type'    => new ListType(new PostType()),
                'args'    => [
                    'title' => [
                        'type' => new StringType()
                    ]
                ],
                'resolve' => ['@app_graph_ql.resolver.post', 'findAll']
            ]
        ]);
    }

}

